import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Container from "~/components/ui/container";
import Header from "~/components/header";

export const metadata: Metadata = {
  title: "Scroll and Transition Playground",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gradient-to-b from-[#FAF0E4] to-[#AAA96E]">
        <Container>
          <Header></Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
